- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages_from_file.yaml
      filename: build
    - include: tasks/packages_from_file.yaml
      filename: tools
