- name: Add apt key
  apt_key:
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- apt_repository:
  state: present
  filename: docker
  repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- apt:
  name: docker-ce
  update_cache: yes
  state: present
