- apt_repository:
  state: present
  repo: ppa:fish-shell/nightly-master

- apt:
  name: fish
  update_cache: yes
  state: present

- get_url:
  url: https://git.io/fisher
  dest: ~/.config/fish/functions/fisher.fish

- command: fish -c 'fisher add edc/bass'
