- name: Add apt key
  apt_key:
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  become: true

- apt_repository:
    state: present
    filename: docker
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
  become: true

- apt:
    name: docker-ce
    update_cache: yes
    state: present
  become: true

- group:
    name: docker
    state: present
  become: true

- user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes
  become: true

#- systemd:
#    name: docker
#    enabled: yes
#  become: true
