- name: Make config directory
  file:
      dest: "{{ ansible_env.HOME }}/.config"
      state: directory

- name: Stow all configs
  command: chdir={{ ansible_env.HOME }}/dotfiles/ansible/stow stow --target={{ ansible_env.HOME }} {{ item }}
  with_fileglob:
      - "stow/*"

- debug:
    msg: "stow/*"
    verbosity: 2
- debug:
    var: item
    verbosity: 2
    with_fileglob:
        - "stow/*"
