- name: Make config directory
  file:
      dest: "{{ ansible_env.HOME }}/.config"
      state: directory

- name: Stow all configs
  command: chdir={{ playbook_dir }}/../stow stow --target={{ ansible_env.HOME }} {{ item.path }}
  with_filetree: "{{ playbook_dir }}/../stow"
  when: (item.path.split('/') | length == 1) and (item.state == 'directory')
