- apt_key:
    id: 7B2C3B0889BF5709A105D03AC2518248EEA14886
    keyserver: keyserver.ubuntu.com
  become: true

- apt_repository:
    state: present
    filename: tor
    repo: deb http://ppa.launchpad.net/webupd8team/tor-browser/ubuntu xenial main
  become: true

- apt:
    name:
      - tor
      - tor-browser
    state: present
    update_cache: yes
  become: true
