#!/usr/bin/env ansible-playbook
- import_playbook: server-full.yaml

- hosts: localhost
  become: true

  tasks:
    - include: tasks/packages_from_file.yaml
      vars:
        filename: desktop
    - include: tasks/packages_from_file.yaml
      vars:
        filename: desktop-full
    - name: Install Steam
      apt:
        deb: http://media.steampowered.com/client/installer/steam.deb
    - name: Install Mailspring
      apt:
        deb: https://updates.getmailspring.com/download?platform=linuxDeb
    - include_tasks: tasks/deluge.yaml
    - include_tasks: tasks/docker.yaml
    - include_tasks: tasks/dropbox.yaml
      #- include_tasks: tasks/google-chrome.yaml
    - include_tasks: tasks/refind.yaml
    - include_tasks: tasks/slack.yaml
    - include_tasks: tasks/spotify.yaml
