#!/usr/bin/env ansible-playbook
- import_playbook: server-full.yaml

- hosts: localhost
  become: true

  tasks:
    - include: tasks/packages_from_file.yaml
      vars:
        filename: desktop
    - include: tasks/packages_from_file.yaml
      vars:
        filename: desktop-full
    - name: Install Steam
      apt:
        deb: http://media.steampowered.com/client/installer/steam.deb
    - name: Install Mailspring
      apt:
        deb: https://updates.getmailspring.com/download?platform=linuxDeb
    - name: Install Deluge
      include_tasks: tasks/deluge.yaml
    - name: Install Docker
      include_tasks: tasks/docker.yaml
    - name: Install Dropbox
      include_tasks: tasks/dropbox.yaml
    - name: Install Chrome
      include_tasks: tasks/google-chrome.yaml
    - name: Install refind
      include_tasks: tasks/refind.yaml
    - name: Install Slack
      include_tasks: tasks/slack.yaml
    - name: Install Spotify
      include_tasks: tasks/spotify.yaml
