#!/usr/bin/env ansible-playbook
- import_playbook: minimal.yaml

- hosts: localhost
  become: true

  tasks:
    - name: Vim ppa
      apt_repository:
        state: present
        repo: ppa:jonathonf/vim
    - include: tasks/packages_from_file.yaml
      vars:
        filename: tools-full
    - include: tasks/packages_from_file.yaml
      vars:
        filename: server
    - include_tasks: tasks/fish.yaml
    - include_tasks: tasks/grive.yaml
